### ISSUE TITLE
Create roundtable plugin

### ISSUE THREAD

**Issue by madmachinations** [kit10-bot/kit10_discord_bot#118]
The roundtable plugin should serve to mediate heated debate.
Proposed command structure:
* `/roundtable on` - Activates roundtable on the current channel
* `/roundtable off` - Deactivates roundtable on the current channel
* `/roundtable join` - Add yourself to the roundtable discussion queue for that channel
* `/roundtable leave` - Remove yourself to the roundtable discussion queue for that channel
* `/roundtable skip` - Mod command to force skip to the next user in the queue
* `/roundtable cooldown @someuser` - Mod command to eject someone from the queue and put them in cool down
* `/roundtable eject @someuser` - Mod command to eject someone from the queue
* `/set roundtable_inactivity_skip_time time_int time_scale` - Mod command to set the time limit someone has to start typing and send a message before they're skipped as outlined below.
* `/set roundtable_cooldown_time time_int time_scale` - Mod command to set the time limit which must elapse before a user in cooldown is allowed to rejoin the queue.

Kit10 should say "It is now someuser's turn to speak, someotheruser is up next." for each turn change, every turn allows that person to post 1 message up to the discord character limit.

If the speaking user doesn't start typing within a time limit, or they start typing and then stop for that time limit, it should skip to the next person in the queue. If a user has to be skipped 3 times they get auto removed from the queue.

If a person makes a post when it isn't their turn, it should get auto deleted and a notification DM should be sent to them. If they're not in the queue it should tell them to run the command `/roundtable join` in that channel to be added to the queue. If they are in the queue it should tell them it's not their turn to speak.

If it isn't their turn to speak and they keep trying to post, they get automatically ejected from the queue for the cool down period

**Comment by VigilanteComedian** [comment]
Roundtable should also perhaps provoke a message in the servers set logs channel as to whether it has been enabled and in which specific room. This does not necessarily need to ping a group of users but could be beneficial for time-tracking issues or the beginning of a conversation.

**Comment by madmachinations** [comment]
@VigilanteComedian can do

**Comment by madmachinations** [comment]
It might also be wise to have a `/roundtable announce SOME TEXT HERE` mod command so that mods can post warnings or whatever without having to disrupt the queue

**Comment by madmachinations** [comment]
There should also perhaps by the option to say `/roundtable CHANNEL` instead of presuming its the channel the command has been run in. To give moderators the ability to run certain commands elsewhere.

**Comment by VigilanteComedian** [comment]
A user variant of the skip command should exist.
Suggest `/roundtable pass` for users who wish to skip their turn whilst they go away to search for things to add to their next message or for more time to read a previous one and reply to it next go.
Users passing their turn should avoid the timeout penalty as it shows they are currently active within that room and acknowledge their turn has come.

**Comment by madmachinations** [comment]
I thought about that @VigilanteComedian, and maybe this will be added in some form in the future. But in the interests of getting a working system tonight they could just say "pass" or drop out of the queue if they know they're not gonna be writing anything for a while
