### ISSUE TITLE
AlertMe Plugin Commands Should Be Excluded From Alerts

### ISSUE THREAD

**Issue by VigilanteComedian** [kit10-bot/kit10_discord_bot#132]
Currently if a user runs the alertme on command and then subsequently adds a word, they will receive a DM alert of the message with the command that's just been executed.
e.g.
`/alertme on
/alertme add_word vigilante`
This would trigger a notification from the bot displaying the relevant information for the "add_word vigilante" command. Whilst this is useful to prove the system works, it's counter-intuitive since the user should already know that specific command has been sent since they just typed it :P

**Comment by madmachinations** [comment]
Will patch tonight
