### ISSUE TITLE
Rewrite ping function for cross platform OS detection

### ISSUE THREAD

**Issue by madmachinations** [kit10-bot/kit10_discord_bot#97]
As it stands the ping function only works on Linux and Mac because windows insists on being special. So OS detection needs putting in here.

**Comment by VigilanteComedian** [comment]
A relatively easy thing to add in. Will do so soon!

**Comment by madmachinations** [comment]
👍

**Comment by VigilanteComedian** [comment]
Issue needs closing since fix has been committed ;)
